project_id = "oqsnzwkiwgqwopuaugxj"

[functions.create-empresa]
verify_jwt = false

[functions.create-master-user]
verify_jwt = false

[functions.orbit-webhook]
verify_jwt = false

[functions.orbit-ai-agent]
verify_jwt = false

[functions.orbit-ai-suggest]
verify_jwt = false

[functions.orbit-send-message]
verify_jwt = false

[functions.orbit-send-email]
verify_jwt = false

[functions.send-orbit-campaign]
verify_jwt = false

[functions.request-campaign-approval]
verify_jwt = false

[functions.send-vendedor-notification]
verify_jwt = false

[functions.orbit-meta-webhook]
verify_jwt = false

[functions.send-orbit-meta-message]
verify_jwt = true

[functions.orbit-search-leads]
verify_jwt = false

[functions.fetch-cnpj]
verify_jwt = false

[functions.add-empresa-user]
verify_jwt = false

[functions.invite-org-user]
verify_jwt = false

[functions.create-empresa-invite]
verify_jwt = false

[functions.accept-invitation]
verify_jwt = false

[functions.validate-invite]
verify_jwt = false

[functions.accept-empresa-invite]
verify_jwt = false

[functions.auto-approve-trial]
verify_jwt = false

[functions.admin-set-password]
verify_jwt = false

[functions.orbit-ai-generate-template]
verify_jwt = false

[functions.orbit-migrate-phones]
verify_jwt = false

[functions.orbit-validate-whatsapp]
verify_jwt = false