// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-prospects.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_prospects_default = defineTool({
  name: "list_prospects",
  title: "List prospects",
  description: "List prospects (leads) for the signed-in user's tenant. Optionally filter by stage or search term. Returns up to 50 records with the most recent activity.",
  inputSchema: {
    search: z.string().trim().optional().describe("Search string matched against name, phone, email, or company."),
    stage: z.string().trim().optional().describe("Filter by pipeline stage id."),
    limit: z.number().int().min(1).max(50).optional().describe("Maximum number of results (1-50, default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, stage, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("orbit_prospects").select(
      "id, nome_razao, telefone, email, documento, empresa_id, pipeline_stage_id, temperatura, valor_estimado, created_at, updated_at"
    ).order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (stage) query = query.eq("pipeline_stage_id", stage);
    if (search) {
      const term = `%${search}%`;
      query = query.or(
        `nome_razao.ilike.${term},telefone.ilike.${term},email.ilike.${term},documento.ilike.${term}`
      );
    }
    const { data, error } = await query;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { prospects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-prospect.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_prospect_default = defineTool2({
  name: "get_prospect",
  title: "Get prospect details",
  description: "Get the full detail of a single prospect (lead) by id, including recent conversations and open tasks. Respects tenant isolation.",
  inputSchema: {
    prospect_id: z2.string().uuid().describe("Prospect UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ prospect_id }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser2(ctx);
    const [{ data: prospect, error: pErr }, { data: tasks }, { data: deals }] = await Promise.all([
      supabase.from("orbit_prospects").select("*").eq("id", prospect_id).maybeSingle(),
      supabase.from("orbit_tasks").select("id, titulo, status, data_vencimento, prioridade").eq("prospect_id", prospect_id).order("data_vencimento", { ascending: true, nullsFirst: false }).limit(10),
      supabase.from("orbit_deals").select("id, titulo, status, valor_estimado, pipeline_stage_id, updated_at").eq("prospect_id", prospect_id).order("updated_at", { ascending: false }).limit(10)
    ]);
    if (pErr)
      return { content: [{ type: "text", text: pErr.message }], isError: true };
    if (!prospect)
      return { content: [{ type: "text", text: "Prospect not found" }], isError: true };
    const payload = { prospect, tasks: tasks ?? [], deals: deals ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-deals.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_deals_default = defineTool3({
  name: "list_deals",
  title: "List deals",
  description: "List deals (opportunities) for the signed-in user's tenant. Optionally filter by pipeline stage. Returns up to 50 deals ordered by most recent update.",
  inputSchema: {
    stage: z3.string().trim().optional().describe("Filter by pipeline stage id."),
    limit: z3.number().int().min(1).max(50).optional().describe("Max results (1-50, default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ stage, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser3(ctx);
    let query = supabase.from("orbit_deals").select(
      "id, titulo, valor_estimado, status, pipeline_stage_id, prospect_id, empresa_id, responsavel_id, created_at, updated_at"
    ).order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (stage) query = query.eq("pipeline_stage_id", stage);
    const { data, error } = await query;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { deals: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-tasks.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_tasks_default = defineTool4({
  name: "list_tasks",
  title: "List tasks",
  description: "List open tasks for the signed-in user's tenant. Filter by status (default: pending). Returns up to 50 tasks ordered by due date.",
  inputSchema: {
    status: z4.enum(["pending", "in_progress", "completed", "cancelled"]).optional().describe("Filter by task status. Default: pending."),
    limit: z4.number().int().min(1).max(50).optional().describe("Max results (1-50, default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser4(ctx);
    const { data, error } = await supabase.from("orbit_tasks").select(
      "id, titulo, descricao, status, prioridade, data_vencimento, prospect_id, deal_id, empresa_id, responsavel_id, created_at, updated_at"
    ).eq("status", status ?? "pending").order("data_vencimento", { ascending: true, nullsFirst: false }).limit(limit ?? 20);
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { tasks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-task.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z5 } from "npm:zod@^4.4.3";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_task_default = defineTool5({
  name: "create_task",
  title: "Create task",
  description: "Create a new task for the signed-in user's tenant. Optionally link it to a prospect and/or deal.",
  inputSchema: {
    titulo: z5.string().trim().min(1).max(200).describe("Task title."),
    descricao: z5.string().trim().max(2e3).optional().describe("Optional description."),
    data_vencimento: z5.string().optional().describe("ISO8601 due date (e.g. 2026-01-15T10:00:00Z)."),
    prioridade: z5.enum(["baixa", "media", "alta"]).optional().describe("Priority."),
    prospect_id: z5.string().uuid().optional().describe("Link to a prospect."),
    deal_id: z5.string().uuid().optional().describe("Link to a deal.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser5(ctx);
    const { data: profile, error: profErr } = await supabase.from("profiles").select("empresa_id").eq("id", ctx.getUserId()).maybeSingle();
    if (profErr)
      return { content: [{ type: "text", text: profErr.message }], isError: true };
    if (!profile?.empresa_id)
      return {
        content: [{ type: "text", text: "User has no empresa_id in profile" }],
        isError: true
      };
    const { data, error } = await supabase.from("orbit_tasks").insert({
      empresa_id: profile.empresa_id,
      responsavel_id: ctx.getUserId(),
      titulo: input.titulo,
      descricao: input.descricao ?? null,
      data_vencimento: input.data_vencimento ?? null,
      prioridade: input.prioridade ?? "media",
      prospect_id: input.prospect_id ?? null,
      deal_id: input.deal_id ?? null,
      status: "pending"
    }).select().single();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Task created: ${data.id}` }],
      structuredContent: { task: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "oqsnzwkiwgqwopuaugxj";
var mcp_default = defineMcp({
  name: "orbit-crm-mcp",
  title: "Orbit CRM",
  version: "0.1.0",
  instructions: "Tools for the Orbit CRM. Read and manage prospects (leads), deals, and tasks for the signed-in user's tenant. All operations are scoped by RLS to the user's empresa (tenant).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_prospects_default, get_prospect_default, list_deals_default, list_tasks_default, create_task_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
